### ISSUE TITLE
Docker data problems

### ISSUE THREAD

**Issue by nelsonblaha** [babybuddy/babybuddy#129]
I've had a hell of a time with the database. Upgrades detached the volume and now I'm trying to start over fresh having given up the first 2 months of my baby's data in an unknown volume. 

I ran the first docker-compose up -d command and got the app container, but the db container is stopped and migration commands fail:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/babybuddy/management/commands/migrate.py", line 10, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
```

Checking the logs for the stopped babybuddy-140_db_1 I see the following over and over:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

Installing 1.4 I have some interest in using a bind instead of a volume so I'll at least be able to keep track of where the data is going forward. For this reason I attempted changing `- db:/db-data:rw` to `- /my/persistent/data/location:db-data:rw` in the services db volumes. When that didn't work I went back to running docker-compose.yml with the minimal changes stipulated in the readme, with the result described above.

I'm getting really lost. I thought I knew how to use docker, but this postgres db container stuff is crazy. I'm grateful for this free software but I must give my two cents: I hate using docker-compose. I'd much rather bind a /data to the container like so many other containers.

**Comment by PTST** [comment]
I struggled for a long time with the same issue.

My docker-compose config now look like this, and it works.
But i honestly cannot tell you which part of it got i working.

```yaml
services:
  db:
    image: postgres
    container_name: db
    environment:
      - PGDATA=/db-data
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /apps/babybuddy_db:/db-data:rw
    networks:
      - baby_network
  app:
    image: babybuddy/babybuddy
    container_name: babybuddy
    # See README.md#configuration for other environment configuration options.
    environment:
      - "ALLOWED_HOSTS=*"
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.docker
      - SECRET_KEY=xxxxxxxx
      - "TIME_ZONE=Europe/Copenhagen"
    volumes:
      - /apps/babybuddy:/app/media:rw
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - baby_network
    links:
      - db:db

networks:
  baby_network:

volumes:
  db: {}
```

**Comment by cdubz** [comment]
@nelsonblaha I'm sorry you've seemingly lost data here. I wish I could be more help with the Docker stuff but it's still very new to me as well. Does @PTST's advice get you anywhere?

There is also someone on [gitter](https://gitter.im/babybuddy/Lobby) with some issues around this. He is attempting an export and import, though that may not be useful to you at this point...

**Comment by zombiehoffa** [comment]
Just so I understand did you originally use docker volumes for your persistent data instead of an explicit local drive mount? PTST is using explicit local drive mounts in his config that works for him and I do the same and have had zero problems (hopefully for good and not so far).

**Comment by cdubz** [comment]
Yes, I believe that is the case. If you look back at [v1.3.0](https://github.com/babybuddy/babybuddy/tree/v1.3.0) you can see the old [`docker-compose.yml`](https://github.com/babybuddy/babybuddy/blob/v1.3.0/docker-compose.yml) file that was included with the repo and it's history, if that helps.

**Comment by 5280Pipedream** [comment]
My import/export errors were because my JSON ids (keys) did not match what version 1.4.0 was looking for, so it turns out that was unrelated to the database.

I was getting similar errors to this when spinning up the new container with docker-compose and then failed at migrate. I fixed the problem by specifying the volumes in the compose file. 

@nelsonblaha Have you specified a user name and password or any other env variables in your docker-compose.yml? Can you post it for review?

My working docker-compse.yml

version: "3.7"
services:
  db:
    image: postgres
    container_name: bb_db
    environment:
      - PGDATA=/db-data
    env_file:
      - docker.env
    volumes:
      - db:/db-data:rw
    ports:
      - 5432:5432
  app:
    image: babybuddy/babybuddy
    container_name: bb_app
    env_file:
      - docker.env
    volumes:
      - media:/app/media:rw
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db: {}
  media: {}

My docker.env file

ALLOWED_HOSTS=*
DEBUG=False
DJANGO_SETTINGS_MODULE=babybuddy.settings.docker
SECRET_KEY=your_secret_key
TIME_ZONE=your_time_zone

**Comment by 5280Pipedream** [comment]
@nelsonblaha - I ran into a similar issue when I tried to move testing from my local machine to my server.

The error

> psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known.

Check if the db container is running using `docker ps`. It's likely only the app is running because the db container failed to start. You can verify this behavior by running `docker-compose up` to see the output of the containers.

The postgres container doesn't start because a password is not set for the user postgres. I'm not sure why running the container locally vs server would make a difference but my guess is that sudo user the docker daemon uses locally vs docker-machine is different. Setting a password in the `docker.env` file with `POSTGRES_PASSWORD=password` doesn't resolve the issue however. When running `docker-compose exec app python manage.py migrate` again the db container will start but the migration.py still fails with an error that the password was not supplied. This time the error is coming from the django application.

I placed `POSTGRES_HOST_AUTH_METHOD=trust` in my `docker.env` file as a work around. 

**This is warned against as it gives anyone open access to the database.** 

[See postgres docker documentation for more]( https://github.com/docker-library/docs/tree/master/postgres#environment-variables.)

After setting the `POSTGRES_HOST_AUTH_METHOD=trust` I was able to run the migrations and initialize the cache.

```
docker-compose exec app python manage.py migrate
docker-compose exec app python manage.py createcachetable
```
After verifying the app was running properly run  `docker-compose down` to remove the containers.

I then removed the `POSTGRES_HOST_AUTH_METHOD=trust` from the `docker.env` file.  **I do not know for sure this actually resets the database setting**. But no password is set for the default user `postgres` anyway.

Running `docker-compose up -d` then gave me access to a fresh instance of the app.

I hope this helps.

**Comment by nelsonblaha** [comment]
@PTST your dockerfile is extremely helpful, thank you! I love that I can alter babybuddy in portainer now that it doesn't have a / in the container name like "babybuddy134_app_1/babybuddy134_db_1".

The only issue I'm having now is with the network. I changed both app and db back to 'bridge' to try to make my nginx proxy virtual_host work again (with the usual virtual_host and virtual_port env variables). I get a 502 when accessing through nginx, which is weird because it used to work fine with those steps in my 1.3..x install. Just in case anyone knows what that's about.
