### ISSUE TITLE
"Today's Naps" card no longer has data

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#136]
Looks like a recent regression, but haven't had a chance to look in to it more.

**Comment by cdubz** [comment]
This is a timezone issue. Looks like something is being converted to UTC somewhere and causing the card to think it is in a different day.

**Comment by phardy** [comment]
I must be missing something here, because I haven't been able to replicate this against current HEAD.

My first test was with fake data, create with

    export DJANGO_SETTINGS_MODULE=babybuddy.settings.development
    gulp migrate
    gulp createcachetable
    gulp fake --children 1 --days 21
    gulp

Upon logging in I see three sleep records for today, 1:17am, 7:35am and 9:35am. The Today's Naps card correctly lists two naps (and also gives the right total nap time). I loaded up the db.sqlite file and looked at the start times in the `core_sleep` table, and see

    2020-05-15 20:54:06.570760
    2020-05-16 01:17:44.570760
    2020-05-16 07:35:07.570760
    2020-05-16 09:35:07.570760

I was a little worried about the times matching up until I realised that the fake data sets the admin user's timezone to UTC.

The next thing I did was to grab a database backup from my production system running 1.3.4 and load it up. Copied db.sqlite across, and did

    export DJANGO_SETTINGS_MODULE=babybuddy.settings.development
    gulp migrate
    gulp

At first this showed that there had been no naps today. But my user has been given the default timezone of `America/Los_Angeles`, when all of my data has been entered with timezone set to `Australia/Sydney`. I changed my user's timezone settings, and got data on the dashboard that matched the production system.

It's probably worth noting that I've always run my production system with a timezone set, with this line in `babybuddy/settings/production.py`

    TIME_ZONE = "Australia/Sydney"

And as a result, all of the times that I've looked at in the database (admittedly only `core_sleep`) seem to be correct UTC.

So I'm not sure what the problem is. Is this a matter of using an old database with times recorded in localtime instead of UTC?

**Comment by cdubz** [comment]
Thanks for looking in to this, @phardy. I'm actually not sure how to reproduce myself but we are currently using the app for our child, working from `master` and every night at some point our naps counter for the day resets to no naps for the day. I just fiddled around with the demo instance and couldn't reproduce the issue at all.

I'll keep an eye on it today and note the specific time that it seems to stop working. I want to say it's around 6PM PT but I can't recall.  In our case we have our server TZ set to `America/Los_Angeles` and I have my user TZ set to that as well.

**Comment by phardy** [comment]
Pacific Daylight is UTC-7, so if it stops working after 5pm then almost certainly crazy TZ shenanigans. :/

**Comment by cdubz** [comment]
Oh yeah that’s right. That is what led me to my assumption about it being a TZ issue. I’m hopeful that’s it’s just something in the card logic that needs to be adjusted.

**Comment by phardy** [comment]
Oh. Yep, there it is. `card_sleep_naps_day()` is getting the date with

    date = timezone.localtime(date).astimezone(timezone.utc)

But just dropping the `astimezone` doesn't affect the test result. I think tweaking the test data should be enough to uncover discrepancies, but it's getting way too late here for me to figure it out. Will hopefully find time tomorrow.
