### ISSUE TITLE
Ability to track Medicine

### ISSUE THREAD

**Issue by rplankenhorn** [babybuddy/babybuddy#153]
Been using Baby Buddy for a few weeks now and really loving it.  One thing that would be great is if you could track medicine administered.  I imagine this would basically be a duplicate of the Diaper Change feature since it doesn't require a duration.  The parameters other than the child would be the medicine and amount in mL.

I may try and tackle this one but wanted to get an issue created to see if anyone else has thought of this or made progress towards this feature.

**Comment by cdubz** [comment]
So there is #66 from a while back. I took a crack at this on a branch but got too far removed on it and had to bail eventually. At the time I had kind of higher hopes for how this could work. What I'd love to be able to do is add some mechanism for alerts and a Medicine model (and related models) to _schedule_ medicines, get alerts, and confirm administration. I actually got pretty far along with this and thinking back I'm annoyed I dropped the branch.

Anyway, I would consider a lighter approach for 1.x -- what you describe could be closer to the Weight model than the Diaper Change (although I think Weight uses a Date field, not DateTime). So the framework for that is pretty much already there. To date I have avoided using units anywhere because I'm not inclined to enforce anything on anyone. E.g. mL may make sense for some medications, but not at all -- and users may have different preferences for units anyway.

What would be the advantage of a specific model for this over using Notes generically? #151 would help make that more useful perhaps (so the date and time for an entry could be customized).

**Comment by rplankenhorn** [comment]
@cdubz Makes sense.  I think the Notes field would be fine for this and I'm honesty so new to Baby Buddy that I missed that field.

#151 would definitely help with this.  Also, I wonder if some sort of custom label/tagging for notes would be a good feature?  Kind of like Github PRs, you could easily create a tag for "Medicine" and allow filtering of the Notes based on that.  This could be a great path for testing out a feature and seeing what fields are important.  Then, add it later if necessary.

> I took a crack at this on a branch but got too far removed on it and had to bail eventually. At the time I had kind of higher hopes for how this could work. What I'd love to be able to do is add some mechanism for alerts and a Medicine model (and related models) to schedule medicines, get alerts, and confirm administration. I actually got pretty far along with this and thinking back I'm annoyed I dropped the branch.

If you still have the same computer and the same baby buddy repo checked out locally, I imagine you would be able to recover this branch using ```git reflog```.  Might be kind of a pain to comb through all your commits but it might be worth it based on what it wounds like you had implemented.

**Comment by cdubz** [comment]
Labeling could be a cool, but that would be a somewhat decent sized feature as well. Smaller than full blown medicine tracking, at least. #151 was added recently in 3f0694dc9d9581895ad63d17e92b0b433de1e303.

**Comment by cdubz** [comment]
Closing in favor of #66 (to the extend this is still relevant given we now have #151 and tags).
