### ISSUE TITLE
How to configure for MySQL?

### ISSUE THREAD

**Issue by sstratoti** [babybuddy/babybuddy#154]
I see that the original install used postgres, and there was a new docker-compose file supplied for sqlite. In the readme it mentions you can use MySQL. How do I go about configuring this in the docker-compose?

Thanks!

**Comment by cdubz** [comment]
Sorry, I suppose the README is a bit misleading there -- I have never actually tested with MySQL and support is not there out of the box (regardless of Docker Compose). Some additional dependencies would be needed to support it. See [Django's documentation for MySQL support](https://docs.djangoproject.com/en/3.1/ref/databases/#mysql-notes) for more. It looks like there are quite a few gotchas generally there. I recommend trying this in a fork initially before we can see if there is any way to support this better in the main package.

**Comment by cdubz** [comment]
I managed to test this seemingly successfully tonight. Using MariaDB in Ubuntu 20.04 --

### Prereqs
```
sudo apt install mariadb-server libmariadb-dev
mysql_tzinfo_to_sql /usr/share/zoneinfo | sudo mysql -u root mysql
pipenv install mysqlclient
cd /path/to/babybuddy/repo
sudo mysql
sql > CREATE database babybuddy CHARACTER SET utf8;
sql > CREATE user 'babybuddy'@'localhost' IDENTIFIED BY 'babybuddy';
sql > GRANT ALL PRIVILEGES ON babybuddy.* TO 'babybuddy'@'localhost';
```

### Add to `development.py` settings file
```
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# https://docs.djangoproject.com/en/3.1/ref/databases/#mysql-notes

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'database': 'babybuddy',
            'user': 'babybuddy',
            'password': 'babybuddy',
            'use_unicode': True,
            'isolation_level': 'read committed',
            'init_command': 'SET default_storage_engine=INNODB',
        },
    }
}
```

### Bootstrap
```
gulp migrate
gulp createcachetable
gulp fake
gulp
```
---

From there I had a seemingly working instance with fake data in MySQL.

**Comment by sstratoti** [comment]
Thanks, this is great! 

Looking for the file, it looks like this is in the /settings directory, each with their own .py configuration file. So we could create a mysql.py and import base, and this would work? Similar to how the docker.py works?

I'm thinking about creating a my.cnf file, similar to whats described in this post:

https://stackoverflow.com/questions/19189813/setting-django-up-to-use-mysql

You can then have a my.cnf file that exists outside of the docker image. You could map a directory as a volume in docker, and reference the internal path to the file in the mysql.py. This way you can set your own IP, database name, user, password, etc - and it'll be outside of the docker image when you pull down a new version. What're your thoughts?

**Comment by cdubz** [comment]
@sstratoti yeah I think that makes sense. The only thing I'm unsure about w.r.t Docker are the "Prereqs" in my comment. I have seen issues in the past with TZ data in Docker images and Baby Buddy is tied strongly to Django's internationalization and localization features so that needs to be well supported.

I agree that a `my.cnf` approach is more appropriate here. We could configure the `mysql.py` settings file to look for that file in the `data` directory at the repo root. That is there for the sqlite support and intended to be mounted as a preserved volume (or whatever it's called) in Docker. Seems like a sensible place to put it?

**Comment by sstratoti** [comment]
@cdubz - I built the docker file locally and verified it's connected. I ran a few test timers / logs and created a new user. I also verified I could switch back to SQLite without an issue in the new docker build file.

This uses an external my.cnf file to supply the MySQL connection properties. You can map it in using a volume in docker-compose. I supplied a sample cnf and docker-compose file for MySQL.

**Comment by sstratoti** [comment]
Sorry, just read your reply. I'll move it under /data in a new commit. 1 sec.

**Comment by cdubz** [comment]
@sstratoti No worries. I don’t think we want to actually put a file there. Just offer it up as part of an example. Everything in that folder is ignored by git.

**Comment by sstratoti** [comment]
oh, ok!
So regarding timezones, I'm not sure what to test with that. I've got my own MySQL docker image up and running that is separate from BabyBuddy. That is using my system timezone for the server.

https://hub.docker.com/_/mysql

MYSQL_INITDB_SKIP_TZINFO
**By default, the entrypoint script automatically loads the timezone data needed for the CONVERT_TZ() function.** If it is not needed, any non-empty value disables timezone loading.

So I think it'll be OK and use whatever timezone is set for the instance of MySQL you're running with. With Postgres and SQLite, you're creating those DBs on the fly, and therefore need to define the timezone. With the my.cnf, you're connecting to an already established MySQL server. It doesn't spin one up with BabyBuddy.

**Comment by sstratoti** [comment]
Actually, I think it does make sense to use /app/data - because we're mapping in that file using the docker-compose volume, right?
I wont move the same file under /data, but I can update the path and the sample docker-compose to /app/data to keep it consistent with the SQLite setup?

**Comment by sstratoti** [comment]
Updated now!

**Comment by sstratoti** [comment]
So I was double checking the "contribute" doc, and I didn't run any of the gulp checks. I'm trying to run them now, but I'm not familiar with it and I'm running into errors. I tried following the steps for development that you outlined, but I'm having an issue with gulp migrate. Can you give it a shot?

**Comment by cdubz** [comment]
No worries about the gulp stuff for now. That is primarily for changes to Baby Buddy itself. We're just working out infrastructure support here.

**Comment by kdrobnyh** [comment]
Now [Babybuddy Docker image from LinuxServer](linuxserver/babybuddy) should be able to support MySQL/MariaDB as well. Check it out.

**Comment by cdubz** [comment]
Thanks, @kdrobnyh. There are still some changes necessary to the application itself. Some of that work was done in https://github.com/babybuddy/babybuddy/pull/155 but it's pretty outdated now and had quite a few issues. I'd be happy to have someone using MySQL to pick that PR back up (or start a new one if its easier).

**Comment by cdubz** [comment]
Oh, maybe less than I thought? I assumed [pymysql](https://pypi.org/project/PyMySQL/) would need to be added to the requirements. What does your `DATABASES` setting look like, @kdrobnyh?

**Comment by kdrobnyh** [comment]
I use (with and without Docker) [mysqlclient](https://pypi.org/project/mysqlclient/). According to the different [sources](https://stackoverflow.com/questions/43102442/whats-the-difference-between-mysqldb-mysqlclient-and-mysql-connector-python), it's much faster than [pymysql](https://pypi.org/project/PyMySQL/) you mentioned. The drawback is it required an additional library installed in the system - mysql-connector-c. In the Docker image, it will be added automatically. However, it might be considered as an optional dependency for BabyBuddy itself if people need MySQL/MariaDB support. In my settings, I use `DB_ENGINE=django.db.backends.mysql` and `DB_HOST=/mysqld.sock`, since you can't specify `OPTIONS` using environmental variables.

**Comment by kdrobnyh** [comment]
@cdubz, what else is needed to close the issue?

**Comment by cdubz** [comment]
Well for Docker it seems we are covered based your experience. I think the only thing maybe worth doing is adding some notes to the documentation about how to configure for Docker and how to do this for non-Docker deployments. Maybe this could be documented under https://docs.baby-buddy.net/setup/configuration/#db_engine or maybe it needs its own separate subsection of Setup?

**Comment by kdrobnyh** [comment]
The way I see it is having a separate subsection, since it requires a separate database setup.
For Docker I use the following:
1. Create a new user and group in the system.
2. Run `mysql_tzinfo_to_sql /usr/share/zoneinfo | sudo mysql -u root mysql`, it does not work otherwise.
3. Create a new user and table in MariaDB using commands similar to ones you mentioned before: 
  ```
  sql > CREATE database babybuddy CHARACTER SET utf8;
  sql > CREATE user 'babybuddy'@'localhost' IDENTIFIED BY 'babybuddy';
  sql > GRANT ALL PRIVILEGES ON babybuddy.* TO 'babybuddy'@'localhost';
  ```
4. Create environment variables file, which contains user, database info, etc:
```
DB_ENGINE=django.db.backends.mysql
CSRF_TRUSTED_ORIGINS=***
DB_HOST=/mysqld.sock
DB_NAME=babybuddy
DB_USER=babybuddy
DB_PASSWORD=***
PUID=***
PGID=***
```
PUID and GUID should be related to user and group created in the system in step 1. That user will be the owner of media and configuration files.
5. Create Docker `babybuddy.yml` configuration:
```
version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    env_file:
      - ***.env
    volumes:
      - ***:/config
      - /run/mysqld/mysqld.sock:/mysqld.sock
    ports:
      - ***:8000
    restart: unless-stopped
```
All `***` should be replaced.
6. Run `docker-compose -f babybuddy.yml up -d --build`

For non-Docker deployment, `production.py` file should be changed accordingly.

**Comment by cdubz** [comment]
Thanks, @kdrobnyh this is a great start. I'll give it a try and work on starting a documentation section soon. For the non-Docker deployments I suspect there are also some additional system packages that will need to be installed but that should be easy enough to figure out.

**Comment by kdrobnyh** [comment]
Oh, small comment: `/run/mysqld/mysqld.sock` might be in a different place, depending on your system.
I believe that the only package needed is `py3-mysqlclient`, package name is also system-specific.
