### ISSUE TITLE
Postgres password concern

### ISSUE THREAD

**Issue by Zutart** [babybuddy/babybuddy#180]
My deployment strategy has multiple docker containers utilizing a single postgres docker container for their database needs. I've created individual users for each service and attached them to their respective tables to ensure no one service could have access to another.

It appears as if this container is hard coded to utilize the root password for the postgres container. Am I incorrect in that assessment? If not, would there be a way to pass both a username and password (and potentially the rest of the variables, such as database name and port)?

**Comment by cdubz** [comment]
Do you mean the settings in the [docker settings file](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/docker.py)? That file looks for a `POSTGRES_PASSWORD` environment variable for the password. Currently, setting the user by environment variable is not supported, but that would be easy enough to change. Would that work for your use case?

**Comment by Zutart** [comment]
I think it would. Essentially, this is an example of another docker image and how i configure its access to postgres:

      - DB_TYPE=postgres
      - DB_HOST=database.postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWORD={password}

That way I can specify a specific server, port, username, pw, and db if any aren't the default values expected and I can better control access to the DB without needing to expose the root password. It may also help with the foundation for this image to be able to use other DB types like MySQL.

Let me know if that helps to better explain my thinking, and appreciate you responding so quickly!

**Comment by cdubz** [comment]
Yeah, I like that approach (exposing all the DB settings as ENV variables). This will require documentation updates as well and we'll want to continue to support `POSTGRES_PASSWORD` until a new major version release. Are you interested in making a PR? No worries if not, I wouldn't mind learning a bit about how/if Python and Django handle deprecation (i.e. for the old env variable).

**Comment by Zutart** [comment]
Actually I would love to, I've only recently been able to fully dive into this world and this is a project I'd love to contribute to given my second is on the way and I REALLY could have used it with number one.

I'll go ahead and get a branch moving on this shortly once I have a break at work and if I can get it figured out (or if someone else can help) we'll get this updated that way.

**Comment by cdubz** [comment]
Cool, thanks. I'll be happy to help if you run in to any trouble. I think the three settings files we'd want to make changes to would be:

1. [base.py](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/base.py)
2. [docker.py](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/docker.py)
3. [production.example.py](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/production.example.py)

I like your format for the environment variable names, but lets use `DB_ENGINE` instead of `DB_TYPE`. All the default engines are in the same namespace (see [setting-DATABASE-ENGINE](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-DATABASE-ENGINE)) but I'd like to support the possibility to set that to a different engine in another namespace as needed.

**Comment by cdubz** [comment]
Fixed by #182.
