### ISSUE TITLE
Feature/UI Request: Only require a single time for feedings

### ISSUE THREAD

**Issue by Stoicmaverick** [babybuddy/babybuddy#192]
It would be nice if the UI would only require a single time for feedings, and if that time/date was auto-populated as current. I can see use cases where a duration of feeding would be useful, but for the most part, time and volume are all you really want to know. It's a small thing, but data entry at 2:15AM on a Wednesday is hard, so anything to simplify the process is nice. Similarly, feeding type (bottle, milk, ect) could be auto-populated from the previous entry, as this is usually consistent, and only a blurry-eyed volume entry was required.

Love the project. Thanks again.

**Comment by cdubz** [comment]
I think this has come up before and it does seem reasonable. Through two babies I don't believe we ever did anything at all with feeding duration information. The key stat here is start time to start time duration (which is used e.g. on the dashboard). I'm not sure off the top of my head how much work would be required to make this change but I'll target it for v1.6.0 on the hope that the changes would be BC. Happy to get a PR for this from anyone eager to take a stab at it!

**Comment by philip-n** [comment]
I'm not sure what is proposed here - dropping one of the time fields or simply making one optional?

I'd argue against dropping it, and in favor of making input easier. Examples:
* prefill both fields based on the current time (maybe start field one minute earlier)
* add `+` and `-` buttons behind the input fields that allow to increase / decrease the time in minute-steps
* configure the time picker widget so that it defaults to showing time selection first (saves a click for everything that you add on the same day)

In my mental model, all entities should have a start time and (optional) end time. Even notes, if I were to use them for "Took a walk of 45 minutes" and wanted to programmatically access the duration.

**Comment by cdubz** [comment]
@philip-n I think those recommendations are all good! It seems like it would serve multiple use cases pretty well (and also just generally improve usability of those form fields.

**Comment by jcgoette** [comment]
Are we saying just the Feeding model? Or every model that currently requires Start and End times?

I agree with pre-populating with `.now()` (similar to how Note and Timer are currently).

**Comment by cdubz** [comment]
Good question. I was only thinking about the Feeding model but some or all of the suggested improvements may make sense for other models as well. I’m open to PRs.

**Comment by jcgoette** [comment]
I think leaving Sleep and TummyTime as they are makes sense (for now?). I will work on PR:

- Default Feeding `start` = `now()`
- Set Feeding `end` `blank = True`

@philip-n's other suggestions (add + and - buttons, configure the time picker widget so that it defaults to showing time selection first) are more general. Should we move to another issue?

**Comment by cdubz** [comment]
Yeah we can break off those enhancements to the timer. I’m hoping at least the “default to time input” part will be easy.
