### ISSUE TITLE
Improve cross-midnight timeline view

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#270]

**Comment by lutzky** [comment]
Moving the description from #229 here for further discussion:

Use case: My "baby shift" is 8PM-2AM, and my partner would like to easily see what happened in the late evening. However, currently the timeline view is hard-split at midnight. So, for instance, scrolling to the bottom and seeing no previous events can be a bit jarring.

Turns out it's not that big of a problem, as it's only particularly interesting for the first few hours after midnight, and at this point the link back to the previous day is still easy to scroll back to.

Options include, in increasing complexity:

- Do nothing, decide this is fine
- Copy the day navigation links from the top of the timeline view to the bottom
- Always include one previous day at the bottom of the timeline view
- Same, but hidden behind a "show yesterday" button (similar to "add nav links at bottom", but lets you scroll between the two days on the same page)
- Add a "load more events" button at the bottom to dynamically load more events to the page (highly unlikely to be worth doing IMO)
WDYT?

**Comment by cdubz** [comment]
How about a "Show yesterday" link at the bottom that just loads the page for yesterday (i.e. does the same thing as the "back" navigation) at the top? Low effort and gets the desired effect without much complexity.

**Comment by lutzky** [comment]
Sure; do you like that better than "copy the day navigation links from the top of the timeline view to the bottom"?

**Comment by cdubz** [comment]
Yes but maybe that would also work as long the date is also at the bottom for context.
