### ISSUE TITLE
UI needs work

### ISSUE THREAD

**Issue by awhillas** [babybuddy/babybuddy#32]
Hey,
Love your work. I'm using BB to track my 3week old sons \<dad joke\>poo-gress</dad joke>. We were very into it during the first week but as we get less and less sleep we're finding the UI is a bit too fiddly (particularly the date/time entry).

I'm a frontender these days (was a Django man myself) and was thinking of redoing the forms to make them easier for tired parents who forget when/what the timer is on/for... you know what i mean.

I see you have a good API setup (have you looked into GraphQL yet?) so i might try and write a frontend app using that. Do some interactive D3.js charts.  Maybe even some [DTW clustering](http://www.rdatamining.com/examples/time-series-clustering-classification) (as feedings are a bit staccato for us).

Anyway, do you think its worth having the front & back in the same repo or should they be separate projects? I'm deploying to Heroku and  not sure how to combine a Django + [Create React App](https://github.com/facebookincubator/create-react-app) (at work we keep them separate but that's a big project and parents would want the simplest deploy i guess?).

word

alex

p.s. these are big words as i might get an hour or two a day in while he's sleeping (if i'm not too sleep deprived myself :)

p.p.s If you have another plan for the frontend? Otherwise i can work independently for now and just talk to the API.

**Comment by cdubz** [comment]
The date/time entry is definitely fiddly when you need to make manual changes. What other issues have you run in to?

Ultimately I would prefer to sort out and make improvements to the existing UI without a big rebuild at this point. But if you want to go big, I think it would make sense to do this on a fork. My intention is to create a 1.0 release with a simple frontend and make (or merge!) improvements further down the road. In our three months of usage so far we have largely found the UI to be good but certainly not perfect. 

A simple deploy is definitely a big focus here. I already think it’s a bit complicated (:

Good luck with the little ones! It’s damn stressful with just one (:

**Comment by awhillas** [comment]
What, having more makes it less stressful...?

**Comment by cdubz** [comment]
😭😭
👶👶
💩💩
💤💤
😭😭
👶👶
💩💩
💤💤
😭😭
👶👶
💩💩
💤💤
🕐 🕜 🕙 🕥 🕚 🕦 🕛 🕧 🕑 🕝 🕒 🕞 🕓 🕟 🕔 🕠 🕕 🕡 🕖 🕢 🕗 🕣 🕘 🕤

**Comment by awhillas** [comment]
:D
I feel ya!
We have stopped tracking all together as the interface is too hard for my partner and i'm not awake all of the time. She tends to input stuff after it happens as shes too frantic while 💩  is going down and the time inputs are too hard to use on a phone (the popup calendar doesn't disappear after you choose a day, you have to click to calendar button again). Also the mother-in-law is here and i havne't even tried to explain it to her.

I'm thinking of making all the combinations of inputs (i.e. left breast, right breast, formula, bottle breast milk, sleep, pooh, wee) into a list of buttons which start/stop the time. If you click one while another is going it ends the previous timer and starts a new one with the new activity. The concept of a timer should be transparent to the user (i.e. they don't need to know about it). This would also help us with the sporadic nature of the: feed -> suck finger -> wind -> feed cycle we go though to get him to feed.

Also, the reporting isn't motivating enough to keep up with the tracking (which adds extra pain). I guess the point is to see if the sleeping patterns ( for me).

Having said that the dashboard is quite useful! To be able to check when the last diaper change was is handy or the last feeding.

**Comment by cdubz** [comment]
I would certainly love to see your ideas for improving the time entry. My wife and I mostly input things as they happen so we rarely ever end up modifying a time, it's very interesting to hear that others use it differently and that is a pain point.

Combination buttons for timers seem like a good idea. Do you have a vision for how it might be organized? I'm just worried about jamming too much in to the timer detail interface.

Re: timers being transparent, do you not use multiple timers at once with more than one child? I set them up this way so that multiple children could be tracked with multiple timers going at once. How would this work if timers were transparent? I think it would require more data (e.g. the child and activity) at the *start*, right?

And yes, I agree that the reporting is pretty bleh. Actually, my biggest motivation for building this app was to create the "sleep pattern" graph, which is kind of neat to see now (3.5 months in) but really not super valuable. I agree that the dashboard is the most useful part of the app, and it's something I want to improve on for customization in the long (e.g. allowing users to enable/disable and re-order cards).

**Comment by pscheit** [comment]
just FYI.. love your conversation :D

**Comment by cdubz** [comment]
It's good stuff and I'm leaving this issue open for further discussion and as a reference point for future decisions about the project.

I actually have recently had need to do a bunch of manual entries now that our little one is in day care and I have a clearer understanding of the concerns @awhillas raises re: data entry, particularly for the time/date fields. It's too cumbersome right now.

**Comment by TheEagle13** [comment]
Although I see this is an old thread, and I'm not sure how much work is still being put into this, I'd like to re-ignite/continue the discussion to see if there are any improvements I might be able to help with in the few months I have left with decent sleep. I'm trying to practice/get my wife to practice using the app so it is familiar when we do need it. 

Here are some of my thoughts:
*Possibility of changing how inputs are done for 'duration' inputs (like length of nap, length of playtime, etc) to have the stop time be current time (like currently coded) then the ability to enter either start time OR duration if you already know how long (my wife loves to set timers for everything so she'll already know if they played for 30 minutes, etc). This could eliminate some of the messing with the finicky calendar.
*Possibility of having start and stop buttons (similar to timer functions) to start and stop a feeding.... Although thinking about this more, the timer function seems to accomplish this.

Also my API game is a little weak, and I'd like to know if there is a way to accomplish my second thought via the API... I plan to create a raspberry pi device with buttons so we can just push a button and have it log the info into the app so we don't have to fumble with/find our phones, just push the button and be done. I'm planning to have a button for diaper changes, one to start feeding and one to stop feeding, but I'm not sure the best way to accomplish this with the API so any guidance would be appreciated there.

Thank you for making such an awesome app!

**Comment by cdubz** [comment]
FYI I moved your API questions in to #76 and I'll give some thoughts on them there.

Not a great deal has changed since this thread, and I'm always happy to accept PRs or detailed thoughts on UI changes.

The datetime selection has indeed been a pain point for some so if you can come up with a good way to handle multiple types of input there, I'm all for it. I have never taken the time to really look in to options for that. All the form interfaces are pretty "dumb" right now so changes can be a little tricky.

The timer should essentially do what you want. You can create any type of timed entry directly from a timer instance. Generally, our process with the little one was to start a timer for whatever we were doing and then initiate the new entry (diaper change, sleep, or breast feeding) from the timer itself. This will auto-fill both the start and end times (and that's part of why I have never put deep effort in to changing the datetime select interface).

**Comment by LuisaGeraghty** [comment]
How do you get to reports from the dashboard? Each time I click around I find more interesting bits and pieces, which is great, but I'm still finding it hard to clearly navigate to these areas, I have no idea how much of what you've made I've yet to see. For example, I found the sleep report by accident, after adding a second child.

Also, if the dashboard only shows one child, I think any entry attempts should either be for that child, or at least default to that child. Or the dashboard should show information for both. I found it a bit confusing.

I still think that any type of entry should be within the same dropdown, or even pulled out so all the categories are at the top level - I don't think that "notes" should be at the same level as "children", as that seems like you're applying the note to both children. I also don't think a "note" or "temperature" is significantly different from an activity in terms of UI because they're both items that have a datetime attached to them.

For reference, my background is in database analysis, but in a really niche simple way. Most of it is working with databases made of workarounds by charities that either don't have the money or training to get users to engage fully with it's potential. So although I'm not directly a UI person, or a deep stats person, my job is to work out how people use the interface, get buy-in from them to actually put the data in (and buy-in from the database team to amend the roadblocks), and produce reports (generally using limited tools - a lot of excel!) that help them market their products (or in this case, learn what makes baby sleep well)! I'm trying to learn python while on mat leave, so hopefully I'll get a chance to look at your existing reports and see if I can build on them.

**Comment by cdubz** [comment]
Thanks for your input!

> How do you get to reports from the dashboard?

Currently there is no way to. The graphs are only accessible for the child view page.

The graphs have never been well represented but they are also kind of a PITA to manage (and poorly written/documented). I’ve actually thought about removing them and just focus on the “dashboard” aspect of the application.

> Also, if the dashboard only shows one child, I think any entry attempts should either be for that child, or at least default to that child.

If there is only one child all entries will default to that child. Do you mean that you think it should default to a specific child if, for example, you navigate to an add entry action from a specific child’s dashboard? I think I like that idea. Could be worth a separate ticket as a feature request.

> I still think that any type of entry should be within the same dropdown, or even pulled out so all the categories are at the top level - I don't think that "notes" should be at the same level as "children", as that seems like you're applying the note to both children.

Could you elaborate on this and maybe try to mock up what your are thinking (if you have a clear enough idea)? I can’t quite envision how this would look.

> I'm trying to learn python while on mat leave, so hopefully I'll get a chance to look at your existing reports and see if I can build on them.

Good luck! This project is basically how I taught myself Python. The graphs might be a bit of a mess... Happy to look at any PRs you want to put together or answer questions. I also have a Gitter chat room for the project if you are so inclined.
