### ISSUE TITLE
iOS 15 web app experience is degraded

### ISSUE THREAD

**Issue by alancyau** [babybuddy/babybuddy#357]
Device: iPhone iOS 15.1
BabyBuddy version: v1.9.3
Installed via Docker from https://github.com/linuxserver/docker-babybuddy.

When browsing to BabyBuddy from iPhone and attempting to use the [Add to Home Screen](https://support.apple.com/guide/shortcuts/add-a-shortcut-to-the-home-screen-apd735880972/ios) function, the icon is no longer the BabyBuddy icon. The icon is essentially a cropped preview of the BabyBuddy main dashboard page.

**Comment by cdubz** [comment]
Thanks for reporting. I suspect this is a regression from https://github.com/babybuddy/babybuddy/pull/312. I was happy to cut back on all the system specific icon stuff with that PR but I suspect at least some of it will need to come back.

**Comment by JoeArcher007** [comment]
I'm just adding in here, that this issue is not related to #312 . (or so I believe it to be)

What is happening is it's not converting the website into a web based app, as it does with iOS 14+ and likely earlier versions. It's creating a shortcut for Safari instead of a standalone instance of the website. So when you hit the home screen button, it's creating a new tab in Safari at that bookmarked spot rather than opening a self contained instance of the website.

My wife still has the home screen app/shortcut on her device, but that may have been prior to me moving the instance to Docker.

**Comment by alancyau** [comment]
@JoeArcher007 I believe you're correct. The Add to Home Screen function within iOS is just bookmarking the website instead of converting it into a web based app. For example, when I scroll up and down within the app, the URL bar shows up. If it was an actual web based app, the URL shouldn't appear.

I'm not sure if this is related to the upgrade from iOS 14 to 15.

**Comment by cdubz** [comment]
Ok yeah I see what y’all mean. The icon should be good now but the URL bar does indeed come up. I don’t think this was an issue before but I also don’t have an iOS 14 device to test with.

Maybe this meta tag is relevant? Not sure if it’s new or not. https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW3

**Comment by cdubz** [comment]
@alancyau @JoeArcher007 I think I've got this sorted now. Just needed some additional tweaks to the manifest file to keep the links inside the PWA container instead of opening a new tab in Safari over it.
