### ISSUE TITLE
Feature Request: Store Baby's Schedule/Routine

### ISSUE THREAD

**Issue by BadCo-NZ** [babybuddy/babybuddy#362]
Hi @cdubz and other users.

We are now nearly 5 months in to being Parents, and since about 4 months of age I created a schedule/routine based off the baby's history and other recommendations that we closely try to follow.

Would other people be interested in storing their routine in babybuddy? I think this would be helpful to share it between other users of the app and give you visual queues of what is next to be done or when the next event is.

Does anyone have suggestions of how this would integrate with the current UI?

Thanks again for your efforts so far @cdubz

**Comment by cdubz** [comment]
@BadCo-NZ what kind of output would you be looking for? Just like a day schedule with times and notes about things to do? Or something else?

I have tried over time to keep the dashboard useful as a window in to baby’s “schedule” with the idea being anyone looking at the dashboard could look at “time since last X” and “average time between X” data to get some insight. But that “stats” data with time between stuff is too hidden away…

**Comment by BadCo-NZ** [comment]
Yes, a day schedule with times, events and details, for example:

```
0800 - Awake
0805 - Nappy change
0810 - Feed 210ml
0830 - Play
0930 - Tummy Time
0955 - Nappy Change
1000 - Sleep 30min
```

I'm not entirely sure what would be the best way to have it integrated. It could simply just be a seperate page where it is lists the schedule, or a tile saying the next upcoming schedule event? I'm hoping some others have clever ideas for this part haha.

**Comment by cdubz** [comment]
Makes sense. Data model is pretty straightforward but I would also be interested in opinions on how to implement. Will leave this open for a bit for feedback.

**Comment by BadCo-NZ** [comment]
No one else has any interest in this and I no longer require it so I'll close the issue for now :smile:
