### ISSUE TITLE
Minutes instead of minutos in Spanish

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#468]
When using the app in Spanish, the "since" times in the home cards aren't properly translated and display "minute(s)" instead of "minuto(s)".

I think this broke around version 1.10 and I don't think we have anything wrong in the Spanish django.po/mo files, but I'm probably wrong.

<img width="456" alt="Screenshot 2022-06-03 at 19 54 15" src="https://user-images.githubusercontent.com/1556349/171920466-61c29ddf-07d3-4e93-9894-e722788bd29d.png">

**Comment by cdubz** [comment]
Looking at [`dashboard/templates/cards/sleep_last.html`](https://github.com/babybuddy/babybuddy/blob/master/dashboard/templates/cards/sleep_last.html) and [`dashboard/templates/cards/sleep_day.html`](https://github.com/babybuddy/babybuddy/blob/master/dashboard/templates/cards/sleep_day.html) (where this does work) it looks like the "last" card just needs to be updated to use [`duration_string`](https://github.com/babybuddy/babybuddy/blob/21b8a737c047b30a1c9a9cd2e50f13eae4dd60f9/core/templatetags/duration.py#L33) for proper translation support, I think.

**Comment by jmunoz94** [comment]
I spent a few hours investigating this issue. It seems that the issue comes from Django translations and it is not exclusive to Spanish (Portuguese is also affected).

For Spanish, "minute" is being translated as "minutos" (which is actually the translation for "minutes") and "minutes" is translated as "minutes" (which is not a Spanish word, so I would guess it was a typo). [These are the relevant lines in their PO file](https://github.com/django/django/blob/main/django/conf/locale/es/LC_MESSAGES/django.po#L1197-L1198).

For Portuguese, translations themselves look OK, but I think the format is slightly off (it does not have the `num` placeholder that other languages have), and I assume that because of that it is not matching these translations. [These are the relevant lines in their PO file](https://github.com/django/django/blob/f0c06f8ab7904e1fd082f2de57337f6c7e05f177/django/conf/locale/pt/LC_MESSAGES/django.po#L1104-L1105).

As an example of a language that shows OK here in babybuddy: [here is the PO for Italian](https://github.com/django/django/blob/f0c06f8ab7904e1fd082f2de57337f6c7e05f177/django/conf/locale/it/LC_MESSAGES/django.po#L1181-L1182). You can see that Italian translations are correct (singular: minuto, plural: minuti) and the format also matches what is in most translation files (and likely in the current version of the relevant code, I did not check).

There are some variants of both Portuguese and Spanish that have good translations (at least for this matter): for Spanish Colombian Spanish is OK ([see here](https://github.com/django/django/blob/main/django/conf/locale/es_CO/LC_MESSAGES/django.po#L1118-L1119)) and for Portuguese Brazilian portuguese looks good ([see here](https://github.com/django/django/blob/f0c06f8ab7904e1fd082f2de57337f6c7e05f177/django/conf/locale/pt_BR/LC_MESSAGES/django.po#L1187-L1188)). Even Mexican Spanish is wrong (and the other two Spanish variants do not even have a PO file as of today).

As an experiment I tried changing Spanish from "es" to "es-co" and Portuguese from "pt" to "pt-br", but apparently "es-co" has yet to be included / had not been included in the Django version that the project uses, and translations default to English. Portuguese BR does work, but since I assume that anyway you won't be exactly eager about doing such a change, I think the best thing to do is to wait for Django to address those issues.

pt | pt-br
---- | ----
<img width="590" alt="image" src="https://user-images.githubusercontent.com/48921408/194738251-01b8a71e-b437-47fd-93a3-16f3018f159a.png"> | <img width="596" alt="image" src="https://user-images.githubusercontent.com/48921408/194738200-4188d0d7-0434-4106-a92d-3d517386c7ef.png">

I did not report the issue to Django because first I registered to their issue tracking/forum, to then read that translation issues should be reported via Transifex. Then registered to Transifex, joined the Spanish team but apparently I have to wait a few days to join. They make it too difficult to (correctly) report an issue for my taste, and since this project also uses Transifex, maybe someone from here could let Django know about this?

You suggest using `duration_string`, but from what I could see, `duration_string` only handles hours, minutes and seconds. And, while we may assume that a baby would not go more than a day without sleeping, eating or such, you never know. If you think that introducing such an implicit limitation is OK, I could go on and update a few cards (the issue is not exclusive to `sleep_last.html`) to use `duration_string`; however, without a confirmation, I would prefer not to introduce a potential bug into the codebase.

As an unrelated note: as part of my debugging, I tried regenerating the MO files and I kept getting an error because of an extra \n in a Spanish translation that is not present in the original (English) string. I was running `pipenv run python manage.py compilemessages` to do so, was I doing it wrong or is this a small translation bug in the app?

```
Execution of msgfmt failed: /Users/jmunoz94/Documents/HacktoberFest/babybuddy/locale/es/LC_MESSAGES/django.po:1946: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
CommandError: compilemessages generated one or more errors.
```

The error vanished after removing the offending \n, but wondering if MO files have not been regenerated recently or I was doing it wrong.

**Comment by cdubz** [comment]
@jmunoz94 thank you for digging some deeply on this!

> I did not report the issue to Django because first I registered to their issue tracking/forum, to then read that translation issues should be reported via Transifex. Then registered to Transifex, joined the Spanish team but apparently I have to wait a few days to join. They make it too difficult to (correctly) report an issue for my taste, and since this project also uses Transifex, maybe someone from here could let Django know about this?

I'm sorry to hear you were discouraged from contributing here. That is frustrating. I also have never used Transifex (or even Django's ticketing system) so I don't have any particular advice or recommendations here.

> You suggest using duration_string, but from what I could see, duration_string only handles hours, minutes and seconds. And, while we may assume that a baby would not go more than a day without sleeping, eating or such, you never know. If you think that introducing such an implicit limitation is OK, I could go on and update a few cards (the issue is not exclusive to sleep_last.html) to use duration_string; however, without a confirmation, I would prefer not to introduce a potential bug into the codebase.

This is a fair point. I don't think there is any reason `duration_string` _shouldn't_ support days so perhaps we should proceed woth both changes here -- updating `duration_string` to support days and updating the relevant cards that are not currently using it.

> As an unrelated note: as part of my debugging, I tried regenerating the MO files and I kept getting an error because of an extra \n in a Spanish translation that is not present in the original (English) string. I was running pipenv run python manage.py compilemessages to do so, was I doing it wrong or is this a small translation bug in the app?

I have also seen odd behavior like this in the past. I think it has something to do with differences between the Django-generated files and those that I sometimes pull from the translation service Baby Buddy uses (POEditor). I highly doubt you were doing anything wrong here.

**Comment by jmunoz94** [comment]
Turns out that `duration_parts` does take days into account, but converts them to hours (I had not paid much attention to the definition of `duration_parts`, my bad). I think that is an OK behavior, so I did not edit that function.

I have put a PR up that should address this. I created a new filter to calculate a delta between a given time and (by default) `now` since I could not find a built-in filter that did that (`timesince` returns a `str`, with the incorrect translations we were discussing here).

Let me know what you think of the approach. Thank you for the extra details!
