### ISSUE TITLE
"No notes found" background doesn't extend to the Tags column

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#469]
See picture when opening the Notes list without any note:
<img width="1417" alt="Screenshot 2022-06-03 at 20 01 55" src="https://user-images.githubusercontent.com/1556349/171920883-b6ba620d-67d4-4bff-88ea-e988e223951a.png">

It also seems like the presence/absence of that background varies per screen, so we might want to normalize that.

**Comment by cdubz** [comment]
This is set by the `colspan` attribute in each of the core `*_list.html` templates (e.g.[ `core/templates/core/note_list.html#L64`](https://github.com/babybuddy/babybuddy/blob/master/core/templates/core/note_list.html#L64)). Any that are wrong just need to be updated with the correct `colspan`. They are probably all wrong now because of the tags updates (:
