### ISSUE TITLE
Issue with vertical axis in Sleep Pattern

### ISSUE THREAD

**Issue by Anoerak** [babybuddy/babybuddy#554]
Datas aren't aligned with the vertical axis. 
e.g. screenshot
![image](https://user-images.githubusercontent.com/79709673/198024772-7fa6f2b2-0ff1-47f0-a6e5-491f0dda5bc6.jpeg)

**Comment by cdubz** [comment]
Thanks for reporting. I can reproduce this in the demo. Seems to be specifically affects days where a previous day's entry does _not_ cross midnight. When that is the case the bars line up correctly but otherwise they are off by a (seemingly random) amount.

**Comment by garyglatfelter** [comment]
It happen on days where sleep does not start (or continue) at midnight. so on days 1 and day 6 of this graph you can see it happening:
![image](https://user-images.githubusercontent.com/51980155/198470492-cfe78112-1d0f-40fc-8dd8-52ac72655e6f.png)

Other than those clues, I don't have any ideas more specifically as to why that might be the case, but I can take a closer look this weekend.

**Comment by Anoerak** [comment]
Hi,
I don't know Python but I look into the code and here is my finding:
in the 'sleep_pattern.py' file, line 40 to 44 is a condition if the previous entry crossed midnight (
`        # Check if the previous entry crossed midnight (see below).
        if adjustment:
            _add_adjustment(adjustment, days)
            last_end_time = timezone.localtime(adjustment["end_time"])
            adjustment = None
`

Well, if you put this section in comment, you'll get a normal behaviour with the graph (eg screenshots).
If someone find a fix and can explain to me this part of the code, I might get some interest in Python and hopefully become a bit more helpfull and contribute to this project :).

<img width="2779" alt="Screenshot 2022-10-30 at 00 24 48" src="https://user-images.githubusercontent.com/79709673/198854600-a20b9f13-adce-4031-b155-27f0ba63d1d5.png">
<img width="2745" alt="Screenshot 2022-10-30 at 00 25 10" src="https://user-images.githubusercontent.com/79709673/198854606-0c55e974-5d38-4def-886d-745876093a3b.png">

**Comment by cdubz** [comment]
Thanks for the research, @Anoerak. This is looking at https://github.com/babybuddy/babybuddy/blob/cba4a2babd1b20962c17a0dbce894b9ebea51608/reports/graphs/sleep_pattern.py#L40-L44

This particular handling has been gone over and changed multiple times and always seems to have one edge case or another. It may be a tough one to try to jump in to with limited Python experience.

> Edit: Oh. That's exactly what you said above. Sorry. Maybe I should get more sleep

@garyglatfelter Almost exactly! You added that you might have time to look in to it, I wasn't so committal haha. Would definitely appreciate any help on this one!

**Comment by garyglatfelter** [comment]
OK. Sorry I keep having trouble getting Heroku to run and I can't get it to run locally. BUT nonetheless, by using the gitpod thing (very neat btw), I have found the issue and I will try my best to explain. Let me know if this makes sense @Anoerak.

The bar graph is stacking durations of time on each day, both awake and sleep.
A transparent bar is added to mark 'awake' time. This transparent awake bar shifts the start of the 1st sleep bar (the visible and labeled bar) by an offset each day. They also are used to make the gaps between sleep times.

Now currently, The 'last_end_time' is keeping track of the last time sleep ended.
When sleep cross midnight from previous day an adjustment is made and handled accordingly so that a sleep bar is split to fill up to the midnight point of that day, and start again at midnight of the next day.

**However**, on the first day that an adjustment isn't made, the last_end_time is still from the day before.

The transparent 'awake' bar is calculated from (start_time of 1st nap) - (last_end_time).  (this is in line 77 through line 80)
So let's say 29th, baby went to sleep 5pm to 9pm.
On 30th, baby sleeps from 3am to 6am.
The transparent bar is calculated to be 18 hours long (0300 minus 2100; I guess if the bar graph is handed a negative value for the bar length, it turns it into the absolute value). So it calculates a transparent 'awake' bar from midnight to 18:00, or 6pm. The colored sleep bar is then stacked starting at 6am. This also explains why the times were not off a consistent amount of time, because it depended on the last sleep end time which varies day to day.
