### ISSUE TITLE
Issue with Tummy time graph bar

### ISSUE THREAD

**Issue by Anoerak** [babybuddy/babybuddy#556]
There is an issue on the Tummy time graph bar report where session above an hour are shown for only the minutes past the hours (1h10min becomes 10min) in the bar legend. 
e.g. screenshots

![image](https://user-images.githubusercontent.com/79709673/198840116-b490ca81-7359-498e-bd1a-79b513f7816f.jpeg)
![image](https://user-images.githubusercontent.com/79709673/198840119-6ce026e8-a75f-4734-9ac0-e6c02e0044e0.jpeg)

**Comment by Anoerak** [comment]
Hi,
Issue's coming from file 'ummytime_duration.py', line 73:
`    return "{}m{}s".format(m, s)
`
Missing hours here ao should be:
`
    return "{}h{}m{}s".format(h,m, s)
`

**Comment by Anoerak** [comment]
I'm not familiar with open source code and team work (newbie in development, actually following a course on JS & React aftter graduating in web development last year).
So if I can help in a more efficient way, I'm all ears :).

**Comment by cdubz** [comment]
Nice catch. Here is where you found the issue: https://github.com/babybuddy/babybuddy/blob/cba4a2babd1b20962c17a0dbce894b9ebea51608/reports/graphs/tummytime_duration.py#L66-L73

It would seem this was intentional to save space and because tummy time _generally_ is not expected to be that long. I think an ideal solution here would be to add support for hours but only display it if necessary. E.g., we don't want `0h10m30s` for a 10 minute, 30 seconds entry.

> I'm not familiar with open source code and team work (newbie in development, actually following a course on JS & React aftter graduating in web development last year).
So if I can help in a more efficient way, I'm all ears :).

Well reporting an issue is an important first step 😄 The next thing we'd want here is pull request to fix the issue. The basic steps to do so would be:

- Fork the repository.
- Make the necessary changes in your fork.
- Open a PR against `master` with your fork.

Let me know if you want to give this a try. Even with limited Python experience this one _should_ be pretty straight forward.

**Comment by Anoerak** [comment]
OK, thanks.
I wrote a condition to display hour when needed and create a PR.
Let me know if I did right or wrong :)

**Comment by cdubz** [comment]
@Anoerak haha yeah sorry about the Dokku test -- don't worry about it. Just something I am trying to get working but haven't yet 😄

#561 resolves this and is merged. Thank you!!
