### ISSUE TITLE
DOC : new value to SECURE_PROXY_SSL_HEADER

### ISSUE THREAD

**Issue by tomamplius** [babybuddy/babybuddy#632]
On the documentation 

I need to replace
```
SECURE_PROXY_SSL_HEADER = True
```
to
```
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
```

https://docs.baby-buddy.net/setup/proxy/#secure_proxy_ssl_header
https://docs.baby-buddy.net/configuration/security/#secure_proxy_ssl_header

**Comment by cdubz** [comment]
@tomamplius this is supported as an environment variable. So if `SECURE_PROXY_SSL_HEADER` is `True` the settings value will be set in the way you suggest.

You can see this behavior here:
https://github.com/babybuddy/babybuddy/blob/5b0763161b97a6047f77e1e8160cc58ea4d71bb4/babybuddy/settings/base.py#L272-L273

This is a bit confusing but the idea is that it allows the value to be set easily as an environment variable (since the actual value required is a tuple).

**Comment by tomamplius** [comment]
great, i understand all now
