### ISSUE TITLE
Failed to save "Diaper change"

### ISSUE THREAD

**Issue by P9k** [babybuddy/babybuddy#651]
My partner and I enjoy using your Android app in conjuction with the self-hosted Babybuddy software - thanks for offering this easy-to-use tool to record everything quickly while "in the midst of it". 😅

After using the app for a couple of days, my partner was unable to save any diaper change on her Android phone (Huawai P30). We tried complete re-install and cache cleaning but the problem persists. (See attached screenshot) The other functionalities work for my partner.

On my Android phone the app works flawlessly and I can track everything.

Do you have any idea what might be the problem and/or a suggestion of what to try? 🙃

![photo_5456566322923161668_y](https://github.com/babybuddy/babybuddy/assets/10435455/3f095aa2-109d-4573-a150-86f2d912e200)

**Comment by cdubz** [comment]
The Android app is maintained over at https://github.com/MrApplejuice/BabyBuddyAndroid/ -- could you report this there?

**Comment by MrApplejuice** [comment]
Hey @P9k  - thank you for the report. I have seen myself, as well, but this one is hard to reproduce. I _think_ this stems from desynchronized clocks between the server and the client, and because babybuddy does not allow events to be created in the future, this fails. The app tries to correct for this by measuring the latency between the server and the client and computing the server-time offset but this could be fragile!

This is a also a particular tricky one to debug however, because I only observed it on a single device that was not my own and all parties involved typically auto-sync their time with some time-server.

Anyhow, I think I can actually do something about this. As @cdubz mentioned, this should be transplanted on the other repo. I will do just this!

**Comment by MrApplejuice** [comment]
@P9k

FYI: If you post a comment on https://github.com/MrApplejuice/BabyBuddyAndroid/issues/35 you will be kept up-to-date with my progress on the issue!
