### ISSUE TITLE
Running replica babybuddy containers

### ISSUE THREAD

**Issue by adampetrovic** [babybuddy/babybuddy#668]
Hi!

I have babybuddy working fine in a single container setup with an external postgres database.

As part of a move towards making my workloads kubernetes based, i'm wanting to see if I can get it working in a HA setup with multiple replica pods with a loadbalancer in front. I figured this should be pretty straightforward with all the state being externalised to the postgres database, however when I try to login to the app it just redirects me to the login page. Checking the session table of the database indicates that sessions are being created when I log in but aren't working when it comes to redirecting to the dashboard.

Thinking that perhaps the SECRET_KEY was being uniquely generated across each container and used as part of the session hash, I have set that to a static value, but I am seeing the same behaviour with that change.

Any other suggestions I should try? I'm guessing this is a Django specific issue, but figured I would reach out here for support.

Thanks!

**Comment by cdubz** [comment]
Hm definitely not an area I am familiar with. Have you tried poking around articles re: running Django in Kubernetes generally? E.g. I skimmed https://mattermost.com/blog/orchestrate-django-application-with-kubernetes/ and https://www.digitalocean.com/community/tutorials/how-to-deploy-a-scalable-and-secure-django-application-with-kubernetes and didn't see any obvious special considerations.

Seems like it _should_ work so it's possible Baby Buddy is doing something here that hinders it...

I'm not familiar enough with Kubernetes to test this effectively but if I had access to environment I could probably help troubleshoot. Otherwise happy to assist however I can with what you figure out testing things.

**Comment by adampetrovic** [comment]
Hey @cdubz, thanks for getting back to me.

Turns out that it was the SECRET_KEY that was the culprit. I had a stale pod that didn't update to use the newly set value. Recreating it made everything work as expected.

Sorry for the runaround.
