### ISSUE TITLE
Community chat 

### ISSUE THREAD

**Issue by billybonks** [babybuddy/babybuddy#765]
is the gitter dead?

Only 4 people here

<img width="524" alt="image" src="https://github.com/babybuddy/babybuddy/assets/1640136/2d066c11-7547-4fe2-86ee-42ac523689f4">

**Comment by cdubz** [comment]
Yeah unfortunately it is pretty dead. It used to have more participation but something messed up my notifications settings when they made the migration to matrix and I lost track of it from there. Open to ideas for alternatives, or to try to revive this one. I liked Gitter/Matrix because it seemed to fit well with self-host/privacy conscious audience of Baby Buddy.

**Comment by billybonks** [comment]
That makes sense, i used Gitter briefly before it joined matrix. just wondering if its easier to discuss in that lobby instead of creating issues for all my questions :)

**Comment by cdubz** [comment]
No objections here! I prefer issues and discussions to chat platforms. Create away.

**Comment by billybonks** [comment]
sounds good, ill try to use the discussions feature. forgot about it.
