### ISSUE TITLE
Unable to create tags in forms

### ISSUE THREAD

**Issue by drewsteinacher** [babybuddy/babybuddy#844]
Hi, I've set up my Baby Buddy instance via the [Home Assistant Add-on](https://github.com/OttPeterR/addon-babybuddy), and it works great overall! Thanks for making this useful tool!

I did run into a strange issue that I could not fully troubleshoot myself after digging through the code a bit.

I cannot add a new tag via any activity form, and when I try, I get the following message:
![image](https://github.com/babybuddy/babybuddy/assets/26029945/87179ab8-1f46-4ba2-b7b8-467f5db02049)

Looking at the console, it appears that it is making a GET request to the root of my local Home Assistant URL, which of course gives a 404:
![image](https://github.com/babybuddy/babybuddy/assets/26029945/8f92ddb3-54cf-4606-9a7b-0d32a67abc87)
```
http://homeassistant.local:8123/api/tags/?name=NewTag
```

Side note: The GET request is expected and is done before the POST request here in `tags_editor.js`:
https://github.com/babybuddy/babybuddy/blob/master/babybuddy/static_src/js/tags_editor.js#L236

Comparing it with other forms that work (e.g. feedings), it sends successful requests to the Add-on's URL:
![image](https://github.com/babybuddy/babybuddy/assets/26029945/bf05c6f8-b544-4d7a-9494-2a578420c824)
```
http://homeassistant.local:8123/api/hassio_ingress/C-qJPCYtQopDWtao3qE40kIWuGnvVl3PfJMCTpvSHys/feedings/4/
```

I suspect this to be a configuration issue of some kind, so I apologize if this is actually a bug for the Add-on repo, but it was difficult for me to isolate where the actual problem was.

Lastly, I'll note that I am able to make tags via the Database Admin area, but that workaround takes a bit longer and may not be an option for non-admin users.

**Comment by cdubz** [comment]
Thanks for reporting. I do think this is a bug (of sorts) that should be handled by the base application but I'm not quite sure yet how...

The issue here is that the building of the API URL is not aware of and does not account for Home Assistant ingress handling. For API routes this [happens in exactly two places](https://github.com/search?q=repo%3Ababybuddy%2Fbabybuddy+%22%7B%25+url+%27api%22&type=code) (for this tag editor and the "API Browser" link in the menu).

It seems we need a way to have some context when creating those URLs but this is where I'm a little unsure about the best approach.

We have the [`HomeAssistant` middleware](https://github.com/babybuddy/babybuddy/blob/e8b48155577ac009a5116c200022f4325ccff3fd/babybuddy/middleware.py#L101) with a wrapper specifically for `build_absolute_uri`. That doesn't really apply here but may be instructive?

I assume the more important question is how the ingress path handling is dealt with for those _working_ examples you provide. I'm actually entirely unsure about that off the hand so figuring that out is probably more important and directly applicable.

CC @OttPeterR @MrApplejuice

**Comment by MrApplejuice** [comment]
Hi @cdubz  - message received. I do not have my home assistant test environment anymore because I needed the room the VM was occupying. But I am setting it up right now to have a look! I can vaguely remember that there was an issue with my middleware, so I think I know where to look. Not sure how complicated it will be though :-/

**Comment by MrApplejuice** [comment]
Thnaks to the magic of SSDs setting up a test-system was rather easy. The problem, indeed is that the ajax_url is not correctly being resolved. On my test-system, the URL to baby buddy is:

http://192.168.0.144:8123/api/hassio_ingress/7gmRwVjYBXc9vRWvLJKy1jeCbzeorcvmbqba_51_oiw/

However, the AJAX queries target 

http://192.168.0.144:8123/api/tags/?name=asdf

and not the ingress URL. So the ingress-middleware I wrote is not quite correct it seems:

https://github.com/babybuddy/babybuddy/blob/08acb747a0078a4a2f5248124d7fa8ea73c917a3/babybuddy/middleware.py#L101-L131

I can probably investigate if there is an easy fix of sorts later this week :-)

**Comment by MrApplejuice** [comment]
Yeah, I actually already did some work because I found some shortcomings in my middleware implementation but could not point to an actual failing example, so just left it as is. The most important thing that my middleware _is_ addressing which is required for the android app, and anything that attempts to use the REST-API is that it fixes the django rest framework URLs. So it at least fixes _something_.

> The API routes in question here use url so maybe we could wrap that as well but I'm confused because that is used in [lots of others places as well](https://github.com/search?q=repo%3Ababybuddy%2Fbabybuddy%20%7B%25%20url&type=code) that seemingly should be impacted by this?

Yes, indeed. This is totally weird... and you are sending me off onto a tangent of reviewing home assistant code now by mentioning this... lol. Gimme a minute.

...

Nope, nothing that would be obvious. Not in the [source code](https://github.com/home-assistant/core/blob/0ad2398bdac494eea5f33db80846e49f63d99f6b/homeassistant/components/hassio/ingress.py) or in the [tests](https://github.com/home-assistant/core/blob/0ad2398bdac494eea5f33db80846e49f63d99f6b/tests/components/hassio/test_ingress.py) that would indicate that any black magic is happening there. Unfortunately it is also really really hard to observe because the traffic gets passed through two very complex systems, with django and home assistant ingress.

----------------------

For the time being I am researching if the "deeper" solution I found back in the days, namely setting the full ingress URL through:

~~~~~~~.py
from django.urls.base import set_script_prefix
set_script_prefix("/" + x_ingress_path.lstrip("/"))
~~~~~~~

might be a more stable solution. I find the current monkey patch used in the middleware, rather messy. However, using `set_script_prefix` strikes right at the heart of django, and I am not 100% sure what the side effects of doing this are.

Anyway, I need my full build and debug pipeline for virtualized home assistant development for this to investigate... so some dev-plumbing is the first course of action here.

## Short todo

Mainly for my book keeping:

- [ ] setup build pipeline that allows easy shipping of locally patched containers to my virtual home assistant instance
- [ ] investigate `set_script_prefix` avenue, replacing the old middleware implementation
- [ ] investigate why the one instance of `data-tags-url="{% url 'api:api-root' %}tags/"` does not work in the current implementation

**Comment by MrApplejuice** [comment]
# Update

I am deep in the rabbit hole now. I think that I found part of the "magic" that is happening. But I am tired now and can only roughly sketch out what I have found.

Comparing the stack traces between a _working_ `{% url %}` and a defunct `{% url %}` call reveals a single different dependency in the call stack:

## Defunct stack

~~~~~~~
[...a very long stack ...]
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
  File "/usr/lib/python3.11/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
  File "/usr/lib/python3.11/site-packages/widget_tweaks/templatetags/widget_tweaks.py", line 36, in as_widget
    html = old_as_widget(widget, attrs, only_initial)
  File "/usr/lib/python3.11/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
  File "/usr/lib/python3.11/site-packages/django/forms/widgets.py", line 275, in render
    return self._render(self.template_name, context, renderer)
  File "/usr/lib/python3.11/site-packages/django/forms/widgets.py", line 280, in _render
    return mark_safe(renderer.render(template_name, context))
  File "/usr/lib/python3.11/site-packages/django/forms/renderers.py", line 29, in render
    return template.render(context, request=request).strip()
  File "/usr/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/defaulttags.py", line 480, in render
    traceback.print_stack(file=f)
~~~~~~~

## Working stack

~~~~~~
[... shortend at the equvalnet line ...]
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/defaulttags.py", line 325, in render
    return nodelist.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.11/site-packages/django/template/defaulttags.py", line 480, in render
    traceback.print_stack(file=f)
~~~~~~

## The difference

`widget_tweaks` ... https://pypi.org/project/django-widget-tweaks/

It seems to be a slightly dormant library, but it introduces an important bug in the url-reverse function of django, where it seems that a widget that is rendered using a function of this library looses access to `current_app = context.request.resolver_match.namespace` , used in the implementation of `class URLNode` in Django's `defaulttags.py`. This then leads to incomplete url reversal _in widgets_. **And the tag-editor is the _only_ custom widget in babybuddy  right now that uses a jinja template** if I am not mistaken, which is the only qualitative difference between the url-calls @cdubz.

Smells like a bug in `widget_tweaks` to me right now... but it is not super trivial to fix, unfortunately!

## The impact

Honestly cannot tell yet... too tired...

**Comment by MrApplejuice** [comment]
I did more digging...

> but I'm still confused on how this even works with regular paths? Maybe some other part of the HA integration deals with that automatically?

Seems you were spot-on. I tested out many many different things in django, but all works to be as expected, including my previous post which I now have hidden to not confuse someone... it was a bit red herring. I ultimately modified django to write the _rendered template_ into a file before serving it through home assistant, and there are no `hassio/ingress/12312312` urls in the babybuddy content. However, when I _hardcode_ any absolute url in a template, so bypassing the entire django reverse-url stuff, those get filtered, too.

I tried this:

~~~~~~~~
<div href="/test" something="/test" something-href="/test">
<a href="/test" something="/test">
~~~~~~~~

Any attribute that ends with `href` will get the hassio-ingress url prepended. And only if it is a absolute URL. So this can be a quick-fix (let the "magic url" end in "-href") but I rather would like to understand the entire mechansim. Reading the homeassistant code did not help yet, I posted a question on their discord to maybe get some pointers...

**Comment by MrApplejuice** [comment]
............ and the answer was outside of Discord @OttPeterR actually would have known it!

https://github.com/OttPeterR/addon-babybuddy/blob/main/babybuddy/root/etc/nginx/templates/ingress.gtpl

There they are! `nginx` is rewriting my urls... I think we can better inline this stuff into the home assistant middleware and remove the custom rewrite rules. We need @OttPeterR here to sync up the efforts. But then we can eliminate all of these bugs for the homeassistant integration in one swoop!

**Comment by cdubz** [comment]
Oooooh what a find! Thank you for digging that up!! It was driving kind of crazy and I'm glad you shared my mild infatuation with it, while also bringing more HA experience 😁 I never would've got to that connection!

**Comment by OttPeterR** [comment]
Hey great sleuthing here!
I'm away on travel for the next ~8 days but I'd be happy to help afterwards. I could review a PR sooner though if you wanted to send one up 😉 
I'm sure a quick chat with ChatGPT or Claude could help with nginx pretty easily

**Comment by MrApplejuice** [comment]
@OttPeterR  - thanks for your update - this will take a little bit anyway, so no worries. Enjoy your - presumed - holidays!?

Also thanks cbudz (no need for a @-pinging). I am on my way fixing this, but I am having some trouble with 
- [x] redirects (fixed)
- [x] double substitutions ("hacked")
- [ ] static folder
- [ ] media folder

The static folder and media folders should be doable, but they are a bit messy, so I am not quite sure how to address them, yet: The problem with those is that they are _meant_ to be statically configured in the `settings.py` module, and there is no obvious way to dynamically rewrite these values without it becoming a very messy solution. I am currently exploring two solutions:

1. Override settings.py setting somehow dynamically afterall (messy, but probably more stable than (2))
2. Monkey-patching the template-tags for static and media paths... (this seems to only fix one use-case, so I think (1) is preferred afterall)

**Comment by MrApplejuice** [comment]
Meh... media and static paths are tricky. They are _meant_ to be static afterall, so they might be cached, reused, built into other strings by plugins. There is no clear place in django to dynamically change the origin based on the ingress-url.

I still will pull these rewrites into python though so that, in the future, it is easier to test the rewrite behavior using babybuddy directly. One can then just send custom headers to babybuddy (like X-Ingress-Path) and check the response with, for example, `curl`. Now, one always has to spin up everything in order to be able to test the rewrite behavior.

**Comment by MrApplejuice** [comment]
Jupps, I tested this a bit. I think this could be a fix. API, tagging from the reporting page, url-reversal in general works. The static and media url substitution is a bit "meh" but does practically not change anything for homeassistant, except that the substitutions can now easily be tested with a dev setup of babybuddy. So I think this is a win-win...
