### ISSUE TITLE
Feature Request: Development Milestones

### ISSUE THREAD

**Issue by zchrykng** [babybuddy/babybuddy#86]
Add tracking for development milestones

**Comment by cdubz** [comment]
I think this is an interesting idea, but is there any consensus version of milestones to use? Searching gives a wide range of results and nothing that clearly seems to be consensus. Though maybe this could be configurable... :thinking:

**Comment by zchrykng** [comment]
Initially it could be freeform. Just a text field with a timestamp of when it was created (able to override so you can set a specific time if you can't log it at that moment).

A future feature could be providing suggestions for what milestones to be looking for with a fuzzy match with the current age of the child, but I don't have a good list that I've found.

**Comment by cdubz** [comment]
An initial freeform approach could be to just use the existing Notes feature. Each note is related to a child and records the time the note was created. The time field could be exposed there to make ti a bit more flexible. And maybe some sort of tagging system could be added, but that gets more complicated.

I would only really want to do milestones specifically with an "advice" type of approach and that would be pretty tough.

**Comment by profucius** [comment]
I hate to resurrect this old ticket, but I was searching through the issues for a feature like this, and this is exactly what I was looking for.

I would love to have a Milestones feature, which could be more specific to generic Notes. I use notes a lot for other purposes, so having the Milestones be separate for things like "first flip over" and "started walking" etc would be such a great feature to have IMO. 

I read through the comments above, and I can see it both ways. Now that it's been 5 years since this was closed I wonder if there is any new thinking that could apply to this? In my line of thinking, perhaps a "Milestone" entry could be under "Measurements" (or "Activities"), and it could utilize the existing Notes feature, but it's entries show only the Milestone type of Notes. So essentially, a Notes filter/view.

I can imagine other features added onto this, like user generated custom fields, for tracking details about the Milestones that the user cares about, etc. But of course those would be secondary/optional to the core functionality mentioned above.

Is this something that is technically feasible?

**Comment by klaptafel** [comment]
Came here by searching just like @profucius and also to say the exact same thing. Milestones would be great, even 'freeform'.
