### ISSUE TITLE
Feature Request: Media Tracking

### ISSUE THREAD

**Issue by zchrykng** [babybuddy/babybuddy#87]
Add ability to track media consumed. Books, songs, television, movies, etc.

**Comment by cdubz** [comment]
I'm not totally sold on this, but maybe only because I have not used the app for kids older than one so this hasn't really come up. I'd be interested to hear from folks who use this for older kids and do want this sort of functionality.

**Comment by zchrykng** [comment]
Yeah, I haven't used it for older children either. Found this project after each of my children turned 1 or more.

Was asking for the functionality because I was thinking it would be useful for us parents with older children. Obviously not required, but media time/count is something that my wife and I are trying to track and I'm not aware of a good tool for it.

**Comment by cdubz** [comment]
That's fair. I kind of envision this app as primarily targeted for kids under one. It doesn't have to be that way, but I also don't want to end up trying to do too much.

I think the "media" would need to be a configurable list to allow caregivers to track anything. So the basic model here would be something that just tracks duration of a user-defined thing. A potential setup would be:

- a "`MediaItem`" model with a single text field for a name.
- a "`MediaTime`" model with a relationship to a `Child`, relationship to a `MediaItem`, datetime start field, datetime end field, and maybe a long notes field.

There isn't really an existing form/template set up to build from for "admin" functions that would fit well for adding `MediaItem` entries (maybe the users form would work...) so that would need to built out as well. But that could be generally useful as there are other "modifiable list" type fields that have been requested.

I probably won't have time to work on this in the near term, so happy to accept PRs from anyone interested in build.
